### ISSUE TITLE
Ajustar los mockups de proyecto académico de acuerdo a revisión del arquitecto Jairo Lavado y Maria Fernanda Avendaño (4 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/proyecto_academico_crud#1]
Se debe realizar ajustes necesarios que se dispongan en la reunión por parte de los arquitectos y dbas, analista y lideres de proyecto y técnico.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de ajuste

**Comment by fabianbarreto02** [comment]
Se anexa mockup con correciones del registro del proyecto 

![Mockup Registro de proyecto académico(4)](https://user-images.githubusercontent.com/43799065/64570405-24bb8d80-d326-11e9-8857-354b32816d0a.png)

**Comment by fabianbarreto02** [comment]
Consulta general 

![Mockup Consulta, inhabilitar y modificación de proyectos académico(8)](https://user-images.githubusercontent.com/43799065/64570438-3e5cd500-d326-11e9-87bf-184a43fa2057.png)

**Comment by fabianbarreto02** [comment]
Consulta basica 

![Mockup Consulta, inhabilitar y modificación de proyectos académico(9)](https://user-images.githubusercontent.com/43799065/64570482-61878480-d326-11e9-8a0c-97274cb1caef.png)

**Comment by fabianbarreto02** [comment]
Historico registros

![Mockup Consulta, inhabilitar y modificación de proyectos académico(1)](https://user-images.githubusercontent.com/43799065/64577268-7cb3bd80-d341-11e9-9ad3-9a2f8357cc5f.png)

**Comment by fabianbarreto02** [comment]
Consulta y modificación Completa basico

![Mockup Consulta, inhabilitar y modificación de proyectos académico(2)](https://user-images.githubusercontent.com/43799065/64577403-dcaa6400-d341-11e9-8cbd-fd3f7cd53a00.png)

**Comment by fabianbarreto02** [comment]
Consulta y modificación Completa registro

![Mockup Consulta, inhabilitar y modificación de proyectos académico(3)](https://user-images.githubusercontent.com/43799065/64577439-f9469c00-d341-11e9-99bd-65e482ecd8b8.png)

**Comment by fabianbarreto02** [comment]
Consulta y modificación Completa acta

![Mockup Consulta, inhabilitar y modificación de proyectos académico(4)](https://user-images.githubusercontent.com/43799065/64577478-1d09e200-d342-11e9-8caa-391b7373e869.png)

**Comment by fabianbarreto02** [comment]
Modificación Realizada

![Mockup Consulta, inhabilitar y modificación de proyectos académico(5)](https://user-images.githubusercontent.com/43799065/64577533-4d518080-d342-11e9-9b63-bd88fd182048.png)

**Comment by fabianbarreto02** [comment]
Inhabilitar proyecto

![Mockup Consulta, inhabilitar y modificación de proyectos académico(6)](https://user-images.githubusercontent.com/43799065/64577591-796d0180-d342-11e9-8313-3fc761a5ad6f.png)

**Comment by fabianbarreto02** [comment]
Inhabilitar realizado

![Mockup Consulta, inhabilitar y modificación de proyectos académico(7)](https://user-images.githubusercontent.com/43799065/64577636-9c97b100-d342-11e9-8dc7-e785e8de4479.png)

**Comment by fabianbarreto02** [comment]
Proyecto inhabilitado

![Mockup Consulta, inhabilitar y modificación de proyectos académico(8)](https://user-images.githubusercontent.com/43799065/64577729-df598900-d342-11e9-8267-a0068599757e.png)

**Comment by fabianbarreto02** [comment]
Se espera revision por parte de @FaustoPuerto  y @mafeave

**Comment by FaustoPuerto** [comment]
Revisados los ajustes, se observa coherencia con lo que solicito

**Comment by mafeave** [comment]
Dada la aprobación por parte del analista, se da por finalizada la tarea.
