### ISSUE TITLE
Desarrollo API CRUD de registro proyecto académico en SGA (8 Horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/proyecto_academico_crud#2]
Se debe realizar el desarrollo del API crud para el manejo de las transacciones de proyecto academico,  el API debe cumplir con los siguientes requerimientos:

- [x] El crud debe cumplir con los lineamientos de la Oficina asesora de sistemas.
- [x] El crud debe contar con el refactor, para que las respuestas sean en formato Json.
- [x] Comprobar si la Api funciona correctamente con Swagger.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by mafeave** [comment]
Se verifica la transacción realizada. Se da por finalizada la tarea.
