### ISSUE TITLE
Crear trasacción de registro calificado y transacción de enfásis

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/proyecto_academico_crud#3]
Crear transacción que permita el registro o actualización de un registro calificado.

**Comment by JuanPiedrahita** [comment]
Guiarse del siguiente [mock-up](https://user-images.githubusercontent.com/43799065/64577439-f9469c00-d341-11e9-99bd-65e482ecd8b8.png)

**Comment by JuanPiedrahita** [comment]
[ #4 transacción para update e inserts de enfasis ](https://github.com/udistrital/proyecto_academico_crud/commit/c418709807786fbf6356a7237fdbb4ae312d12c8)

**Comment by JuanPiedrahita** [comment]
[ #4 transacción para update e inserts de registros ](https://github.com/udistrital/proyecto_academico_crud/commit/c43dcbd2a4d2397903c388fcce986c524cff6776)

**Comment by JuanPiedrahita** [comment]
Se agrega data para probar transacciones en el [documento](https://docs.google.com/document/d/1XkxhMLoElzdc2SMw0p9R5FMPbkg0f2zBvBZZz4MliEQ/edit?usp=sharing).

**Comment by JuanPiedrahita** [comment]
Se solicita revisión y validación de las transacciones con @fabianbarreto02

**Comment by JuanPiedrahita** [comment]
SE valida transacción en el sprint review, se da por terminada la tarea.

**Comment by mafeave** [comment]
Se valida la transacción, se da por terminada la tarea.
