### ISSUE TITLE
Agregar informacion de nivel en proyecto_academico_crud y modificacion de la tabla nivel de formacion

### ISSUE THREAD

**Issue by Camiloqui** [udistrital/proyecto_academico_crud#31]

**Comment by Camiloqui** [comment]
### **modificacion de api proyecto_academico_crud**
se necesitaba agregar mas campo en el nivel de formacion, y modificar la tabla nivel_formacion agregando una columna llamada nivel_formacion_padre_id donde se va a auto llamar donde los nuevos inserts seran hijos del las que ya estaban "pregrado" y "postgrado" 
**inicial mente se modifica la tabla del modelo agregando el nuevo campo columna**
aqui con ayuda de bee creamos la migracion desde la consola de comando, ya luego creamos dos scripts para el up() y down() del mismo migrate 
![image](https://user-images.githubusercontent.com/19983790/103697528-a85eac00-4f65-11eb-9952-f96ec8b60410.png) 
dentro del up()
![image](https://user-images.githubusercontent.com/19983790/103697571-b57b9b00-4f65-11eb-813e-35c84ee091ad.png)

hacemos una modificacion de la tabla nivel_formacion y agregamos una columna nueva llamada nivel_formacion_padre_id luego la hacemos llave foranea de ella misma.

En el down() 
![image](https://user-images.githubusercontent.com/19983790/103697668-dba13b00-4f65-11eb-919a-bc62f8912b78.png)
lo que hacemos es elminiar la relacion de la llave foranea con la misma tabla y luego borramos la columna, solo en caso de ocurrir algun error.
En el migration creado en el up() 
![image](https://user-images.githubusercontent.com/19983790/103697796-0b504300-4f66-11eb-860c-d5322bc2aa67.png)
 creamos el codigo que lee el script y queda listo para ser ejecutado cuando se corran todas las migraciones mientras que en el down le agregamos tambien el script para revertir alguna de esas migraciones, ya sea por fallas
![image](https://user-images.githubusercontent.com/19983790/103698346-d7c1e880-4f66-11eb-9a0b-c3931872a800.png)

**modificacion en el modelo**
![image](https://user-images.githubusercontent.com/19983790/103698400-ef00d600-4f66-11eb-88ba-a5f4c550631d.png)
en el modelo nivel_formacion debemos realizar una modificacion
![image](https://user-images.githubusercontent.com/19983790/103698466-02ac3c80-4f67-11eb-9100-95108c059cad.png)
donde agregamos un campo mas llamado NivelFormacionPadreId y se referencia a ella misma, el dato es de tipo fk

**inserts de nuevos campos en la tabla**
Aqui creamos con ayuda del bee otra migracion y la llamamos inserts_tabla_nivel_formacion
![image](https://user-images.githubusercontent.com/19983790/103698642-3dae7000-4f67-11eb-9fef-7609bbc2b79c.png)
luego creamos los scritps correspondientes al up() y down() del archivo creado
**script up() inserts**

**Comment by Camiloqui** [comment]
**script up() inserts**
![image](https://user-images.githubusercontent.com/19983790/103698743-6898c400-4f67-11eb-9fdd-28a3e939b964.png)
en este primer up lo que realizamos es los inserts nuevos, en total son 6 campos, donde los agregamos segun los datos requeridos por la tabla y el nuevo atributo creado en la tabla

**script down() inserts**
![image](https://user-images.githubusercontent.com/19983790/103698816-89f9b000-4f67-11eb-937a-ec5e5c803833.png)para el reverse de los inserts creados
**migration de inserts**
![image](https://user-images.githubusercontent.com/19983790/103699439-89154e00-4f68-11eb-9b5d-6e2b69c0b6ea.png)
en el metodo up() llamamos el script que creamos y lo corremos tambien ejecutamos si presenta algun error
![image](https://user-images.githubusercontent.com/19983790/103699513-acd89400-4f68-11eb-9edd-a499ac69fd02.png)
realizamos lo mismo para el down()

### se realizan pruebas de manera local y en la base de datos se corre correctamente las nuevas migraciones 
![image](https://user-images.githubusercontent.com/19983790/103699600-d0034380-4f68-11eb-978a-ab6735f6aaea.png)
![image](https://user-images.githubusercontent.com/19983790/103699650-de515f80-4f68-11eb-8bdc-ef577a1f2207.png)

**Comment by fabianbarreto02** [comment]
se revisa la issue y se realiza el despliegue en test
