### ISSUE TITLE
Crear trasacción de modificación de la información básica para proyecto académico

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/proyecto_academico_crud#4]
Crear transacción que permita la modificación de la información básica de un proyecto curricular

**Comment by JuanPiedrahita** [comment]
Guiarse del siguiente [mock-up](https://user-images.githubusercontent.com/43799065/64577403-dcaa6400-d341-11e9-8cbd-fd3f7cd53a00.png)

**Comment by JuanPiedrahita** [comment]
Se agrega data para probar transacciones en el [documento](https://docs.google.com/document/d/1XkxhMLoElzdc2SMw0p9R5FMPbkg0f2zBvBZZz4MliEQ/edit?usp=sharing).

**Comment by JuanPiedrahita** [comment]
Se solicita revisión y validación de las transacciones con @fabianbarreto02

**Comment by JuanPiedrahita** [comment]
SE valida transacción en el sprint review, se da por terminada la tarea.

**Comment by mafeave** [comment]
Se valida transacción, se da por terminada la tarea.
