### ISSUE TITLE
Ajustar modelo, api y migrations por ajuste de funcionalidad de asignación de coordinador 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/proyecto_academico_crud#42]
Se debe realizar el ajustes del modelo de datos actual, cambiando el nombre del campo persona_id, por tercero_id, eliminar el campo rol_id, ajustar el modelo del api y crear el migrations con los ajustes correspondientes, la issue debe cumplir con los siguientes requerimientos:

- [x] Actualizar el modelo de datos (imagen, sql, dbm) subirlos a a carpeta https://drive.google.com/drive/u/0/folders/1zAQQet7NNoNhBCrP6U147DO1bsxfcbWG
- [x] Ajustar el api (modelo) con los ajustes correspondientes 
- [x] Incluir el migrations y probar con los ajustes realizados

**Comment by JQuinteroC** [comment]
Se inicia la issue

**Comment by JQuinteroC** [comment]
se concluye desarrollo, a la espera de revisión

**Comment by fabianbarreto02** [comment]
Se realiza el despliegue de los cambios en ambiente de test y se revisa los ajustes solicitados, se da por finalizada la issue
