### ISSUE TITLE
Ajustar modelo de datos y API de proyecto_academico incluyendo el campo de fecha de finalización del coordinador - 5 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/proyecto_academico_crud#7]
Se debe agregar un campo en el modelo de datos de proyecto_academico donde se pueda manejar la fecha de finalización del rol de coordinador, al momento de asignar un nuevo coordinador al proyecto. La issue debe cumplir con los siguientes requerimientos:

- [x] Actualizar el modelo de datos, anexar la nueva versión del modelo.
- [x] Actualizar la Api agregando el campo en el modelo y ajustar el controlador correspondiente.
- [x] Actualizar el scripts para beego migrations.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de ajuste

**Comment by fabianbarreto02** [comment]
Se realiza el primer check, este se puede observar en [drive](https://drive.google.com/drive/folders/1Xpl6SUZmomFqVnpIGFnh0zwh6DWnb4e8)

**Comment by fabianbarreto02** [comment]
Se realiza el segundo check, revisar el commit 7b0aaa7

**Comment by fabianbarreto02** [comment]
Se realiza el tercer check, revisar el commit 15ce93b

**Comment by fabianbarreto02** [comment]
Se revisa el funcionamiento del bee migrations, se da por finalizada la issue, se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se verifican ajustes del API y del modelo con beego migrations.
Se sugiere que para futuros cambios en los modelos de datos, se genere un nuevo archivo de migración, no sobrescribir el script base del repositorio.

Se da por finalizada la tarea.
