### ISSUE TITLE
Pruebas unitarias API CRUD de proyecto_académico tablas paramétricas - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/proyecto_academico_crud#8]
Se debe desarrollar las pruebas unitarias para los controladores que manejen tablas parametricas,  la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar los scripst de test para cada controlador.
- [x] Realizar los test donde se evidencie el correcto funcionamiento de los controladores.
- [x] Realizar las pruebas con la libreria Godog.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67589829-04e9f880-f71f-11e9-86c4-89df94fd9fde.png)

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67590486-cce3b500-f720-11e9-86e2-76ff4c8e6bbc.png)

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67598134-6ff0fa80-f732-11e9-87fb-d98d9a9aaa52.png)

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67599966-c5c7a180-f736-11e9-864c-bc3bedb889d3.png)

**Comment by fabianbarreto02** [comment]
![imagen](https://user-images.githubusercontent.com/43799065/67600660-23102280-f738-11e9-805f-658ad3a799b2.png)

**Comment by fabianbarreto02** [comment]
Se da por terminado la issue, se realiza en total 5 pruebas a los controladores con tablas parametricas del api, se espera revisión por parte @mafeave

**Comment by mafeave** [comment]
Se verifica la realización de las pruebas para los modelos correspondientes a las tablas paramétricas.
Se da por finalizada la tarea.
